WIP - Foxy
clearpathrobotics/public-rosdistro pull request #434
Opened 2021-02-17 21:23 UTC by dniewinski

2021-02-17 21:33 UTC, tonybaltovski requested changes

2021-02-17 21:33 UTC, tonybaltovski commented on index.yaml
> +  noetic:
Shouldn't this be foxy?

2021-02-18 15:20 UTC, dniewinski commented on index.yaml
> +  noetic:
Yup

2021-02-19 17:21 UTC, tonybaltovski approved these changes

2021-02-19 17:22 UTC, merged